### PR TITLE
Add CI job for testing against the starter repo

### PR DESCRIPTION
**Pull request by jagthedrummer**
This make it so that the GitHub Actions CI pipeline will:

* Checkout the starter repo. We'll look for a branch on the starter repo that matches the name of the branch being tested. If we can't find one we'll test against the `main` branch.
* Checkout the `core` repo, also looking for a matching branch.
* Alter the `Gemfile` in the starter repo to point to the local branch of `jbuilder-schema` and the `core` gems.
* Run the Minitest suite of the starter repo
* ~Run the Super Scaffolding suite of the starter repo~ Edit: I'm not sure it's useful to run the Super Scaffolding tests, so I'm skipping it for now.

### CODE REVIEW

**Comment by jagthedrummer** [comment]
@newstler This should be good to go for running tests against the starter repo. There's one test failing on this PR related to https://github.com/bullet-train-co/jbuilder-schema/issues/74 but this doesn't change any shipped code so it should be safe to merge.

**Comment by newstler** [comment]
@jagthedrummer How urgent is this? I would wait when #74 is resolved if possible (we're looking for solution with @kaspth) to be able to release next versions with green tests.

**Comment by jagthedrummer** [comment]
@newstler not super urgent. I just figured that we should get this going sooner rather than later since we kept finding issues after a release instead of before.

**Comment by jagthedrummer** [comment]
@newstler looks like #74 is now resolved, so I rebased this branch and now it looks like everything is good to go.

**Comment by newstler** [comment]
@jagthedrummer Released this as v2.6.7 so should be good to check in BT gems without updating the minor version number.

**Pull request merged**
